name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write .env File
        run: echo -e "${{ vars.ENV_FILE }}" > .env

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.APP_NAME }}:latest .

      - name: Save Docker Image
        run: docker save ${{ vars.APP_NAME }}:latest | gzip > ${{ vars.APP_NAME }}.tar.gz

      - name: Transfer Image to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ vars.VPS_KEY }}
          source: "${{ vars.APP_NAME }}.tar.gz"
          target: "~/"

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ vars.VPS_KEY }}
          script: |
            docker stop ${{ vars.APP_NAME }}-container || true
            docker rm ${{ vars.APP_NAME }}-container || true
            gunzip -f ~/${{ vars.APP_NAME }}.tar.gz
            docker load < ~/${{ vars.APP_NAME }}.tar
            docker run -d --name ${{ vars.APP_NAME }}-container -p 80:5000 ${{ vars.APP_NAME }}:latest
            docker system prune -f
